spring:
    application:
        name: boot2
krpc:
    enabled: true
    registry:
          type: consul
          addrs: 127.0.0.1:8500
    server:
          port: 6500
    service:
          interfaceName: com.xxx.userservice.proto.UserService
